sudo: false

language: cpp

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
	- meson
    env:
    - COMPILER="CXX=g++-8"

  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-6.0
	- meson
    env:
    - COMPILER="CXX=clang++-6.0"
      
notifications:
  email: false
  
before_install:
- eval $COMPILER

script: $CXX --version
