sudo: false

language: cpp

matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - numdiff
    env:
    - COMPILER="CXX=g++-8"
    - PLATFORM="lapack"
    - WITH_MKL="false"

  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
        - clang-6.0
        - numdiff
    env:
    - COMPILER="CXX=clang++-6.0"
    - PLATFORM="lapack"
    - WITH_MKL="true"
      
notifications:
  email: false
  
before_install:
- eval "$COMPILER"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -p _miniconda;  else  wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh && bash Miniconda3-latest-MacOSX-x86_64.sh -b -p _miniconda; fi
- export PATH="$PWD/_miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create --yes -n pi-peps
- conda activate pi-peps
- conda install meson
- conda install -c conda-forge arpack
- conda install mkl mkl-include
- export CPATH=$CONDA_PREFIX/include:$CPATH
- export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
- export PEPS=$PWD
- cd ..
- export SRC=$PWD
- mkdir deps && cd deps && git clone https://github.com/ITensor/ITensor.git itensor && cd itensor
- git checkout 6c96c858a10c641ba052627936cc8850b5155bab
- echo "CXX="$CXX
- sed "s/^CCCOM=.*/CCCOM=$CXX -m64 -std=c++11 -fPIC/" options.mk.sample > options.mk
- sed -i "s/^PLATFORM=/#PLATFORM=/g" options.mk
- sed -i "s/^BLAS_LAPACK_LIBFLAGS=/#BLAS_LAPACK_LIBFLAGS=/g" options.mk
- sed -i "s/^BLAS_LAPACK_INCLUDEFLAGS=/#BLAS_LAPACK_INCLUDEFLAGS=/g" options.mk
- sed -i "s/^#PLATFORM=$PLATFORM/PLATFORM=$PLATFORM/" options.mk
- export flag_line_no=`grep -n PLATFORM=lapack options.mk | cut -f1 -d:`
- sed -i "$(( flag_line_no + 1 )) s/^#BLAS_LAPACK_LIBFLAGS=/BLAS_LAPACK_LIBFLAGS=/" options.mk
- sed -i "s/ITENSOR_MAKE_DYLIB=0/ITENSOR_MAKE_DYLIB=1/" options.mk
- make -j 2
- export LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH
- cd unittest && make
- cd $PEPS
script: 
- CXX=$CXX meson -Ditensor-dir=$SRC/deps/itensor -Dopenmp=false -Dmkl=false -Darpack=false -Dbuildtype=debug -Denable-tests=true -Dlapack-dir=$CONDA_PREFIX build && cd build && ninja -j1
- ldd libpi-peps.so
- meson test --suite unit-tests -v
- meson configure -Darpack=true
- meson test --suite unit-tests -v
- meson test --suite integration --timeout-multiplier=10 -v
